### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [openSUSE/libgnomesu#1]
I would like to point out that identifiers like "[`_LIBGNOMESU_H_`](https://github.com/openSUSE/libgnomesu/blob/b7d2ea9072cec19e30dfd2ac5c7345066f98d49d/src/libgnomesu.h#L20)" and "[`__gnomesu_consolehelper_service_new`](https://github.com/openSUSE/libgnomesu/blob/b7d2ea9072cec19e30dfd2ac5c7345066f98d49d/src/services/consolehelper.h#L27)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by scarabeusiv** [comment]
Basically, this project is in long-term maintenance mode, thus if you find an issue you are free to patch it. There is no active development planned.

**Comment by plusky** [comment]
Not really a issue and outside of scope of this project

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by scarabeusiv** [comment]
Well feel free to patch it, nobody will stop you from that.

**Comment by plusky** [comment]
@elfring as mentioned several times above - this project is in maintenance/legacy mode, thus general improvements of coding style are out of scope of reporting issues here - but in case it bothers you feel free to open pull request. That being said I am locking this conversation.
